Add manifest verification to deployment workflow
A new step has been introduced in the Github Actions deployment workflow that verifies the existence of the manifest.json file and prints its content for debugging purposes. Also enhanced the clarity of the application build step name for better understanding.

diff --git a/.github/workflows/deploying.yml b/.github/workflows/deploying.yml
--- a/.github/workflows/deploying.yml
+++ b/.github/workflows/deploying.yml
@@ -23,6 +23,16 @@ jobs:
       - name: Build Vue.js app
         run: npm run build
 
+      - name: Verify manifest
+        run: |
+          if [ ! -f dist/manifest.json ]; then
+            echo "Manifest not found!"
+            exit 1
+          else
+            echo "Manifest found:"
+            cat dist/manifest.json
+          fi
+
       - name: Setup SSH Agent
         uses: webfactory/ssh-agent@v0.5.4
         with:
@@ -44,7 +54,7 @@ jobs:
       - name: Run npm install
         run: ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.USER_NAME }}@${{ secrets.HOST_NAME }} 'cd /home/keypractica/fe_server && npm install'
 
-      - name: Build application
+      - name: Build application on server
         run: ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.USER_NAME }}@${{ secrets.HOST_NAME }} 'cd /home/keypractica/fe_server && npm run build'
 
       - name: Start the service
